package main

import (
	"strings"
)

var flagMap = map[string]string{
	"afghanistan": "🇦🇫",
	"albania": "🇦🇱",
	"algeria": "🇩🇿",
	"andorra": "🇦🇩",
	"angola": "🇦🇴",
	"antigua and barbuda": "🇦🇬",
	"argentina": "🇦🇷",
	"armenia": "🇦🇲",
	"australia": "🇦🇺",
	"austria": "🇦🇹",
	"azerbaijan": "🇦🇿",

	"bahamas": "🇧🇸",
	"bahrain": "🇧🇭",
	"bangladesh": "🇧🇩",
	"barbados": "🇧🇧",
	"belarus": "🇧🇾",
	"belgium": "🇧🇪",
	"belize": "🇧🇿",
	"benin": "🇧🇯",
	"bhutan": "🇧🇹",
	"bolivia": "🇧🇴",
	"bosnia and herzegovina": "🇧🇦",
	"botswana": "🇧🇼",
	"brazil": "🇧🇷",
	"brunei": "🇧🇳",
	"bulgaria": "🇧🇬",
	"burkina faso": "🇧🇫",
	"burundi": "🇧🇮",
	"bulgarian": "🇧🇬",

	"cambodia": "🇰🇭",
	"cameroon": "🇨🇲",
	"canada": "🇨🇦",
	"cape verde": "🇨🇻",
	"central african republic": "🇨🇫",
	"chad": "🇹🇩",
	"chile": "🇨🇱",
	"china": "🇨🇳",
	"colombia": "🇨🇴",
	"comoros": "🇰🇲",
	"congo": "🇨🇬",
	"costa rica": "🇨🇷",
	"croatia": "🇭🇷",
	"cuba": "🇨🇺",
	"cyprus": "🇨🇾",
	"czech republic": "🇨🇿",

	"denmark": "🇩🇰",
	"djibouti": "🇩🇯",
	"dominica": "🇩🇲",
	"dominican republic": "🇩🇴",

	"ecuador": "🇪🇨",
	"egypt": "🇪🇬",
	"el salvador": "🇸🇻",
	"equatorial guinea": "🇬🇶",
	"eritrea": "🇪🇷",
	"estonia": "🇪🇪",
	"eswatini": "🇸🇿",
	"ethiopia": "🇪🇹",

	"finland": "🇫🇮",
	"france": "🇫🇷",

	"gabon": "🇬🇦",
	"gambia": "🇬🇲",
	"georgia": "🇬🇪",
	"germany": "🇩🇪",
	"ghana": "🇬🇭",
	"greece": "🇬🇷",
	"grenada": "🇬🇩",
	"guatemala": "🇬🇹",
	"guinea": "🇬🇳",
	"guinea-bissau": "🇬🇼",
	"guyana": "🇬🇾",

	"haiti": "🇭🇹",
	"honduras": "🇭🇳",
	"hungary": "🇭🇺",

	"iceland": "🇮🇸",
	"india": "🇮🇳",
	"indonesia": "🇮🇩",
	"iran": "🇮🇷",
	"iraq": "🇮🇶",
	"ireland": "🇮🇪",
	"israel": "🇮🇱",
	"italy": "🇮🇹",

	"jamaica": "🇯🇲",
	"japan": "🇯🇵",
	"jordan": "🇯🇴",

	"kazakhstan": "🇰🇿",
	"kenya": "🇰🇪",
	"kiribati": "🇰🇮",
	"kuwait": "🇰🇼",
	"kyrgyzstan": "🇰🇬",
	"kosovo": "🇽🇰",

	"laos": "🇱🇦",
	"latvia": "🇱🇻",
	"lebanon": "🇱🇧",
	"lesotho": "🇱🇸",
	"liberia": "🇱🇷",
	"libya": "🇱🇾",
	"liechtenstein": "🇱🇮",
	"lithuania": "🇱🇹",
	"luxembourg": "🇱🇺",

	"madagascar": "🇲🇬",
	"malawi": "🇲🇼",
	"malaysia": "🇲🇾",
	"maldives": "🇲🇻",
	"mali": "🇲🇱",
	"malta": "🇲🇹",
	"mexico": "🇲🇽",
	"mongolia": "🇲🇳",
	"morocco": "🇲🇦",
	"mozambique": "🇲🇿",
	"myanmar": "🇲🇲",

	"namibia": "🇳🇦",
	"nepal": "🇳🇵",
	"netherlands": "🇳🇱",
	"new zealand": "🇳🇿",
	"nicaragua": "🇳🇮",
	"niger": "🇳🇪",
	"nigeria": "🇳🇬",
	"north korea": "🇰🇵",
	"norway": "🇳🇴",

	"oman": "🇴🇲",

	"pakistan": "🇵🇰",
	"panama": "🇵🇦",
	"paraguay": "🇵🇾",
	"peru": "🇵🇪",
	"philippines": "🇵🇭",
	"poland": "🇵🇱",
	"portugal": "🇵🇹",
	"palestine": "🇵🇸",

	"qatar": "🇶🇦",

	"romania": "🇷🇴",
	"russia": "🇷🇺",
	"rwanda": "🇷🇼",

	"saudi arabia": "🇸🇦",
	"senegal": "🇸🇳",
	"serbia": "🇷🇸",
	"singapore": "🇸🇬",
	"slovakia": "🇸🇰",
	"slovenia": "🇸🇮",
	"somalia": "🇸🇴",
	"south africa": "🇿🇦",
	"south korea": "🇰🇷",
	"spain": "🇪🇸",
	"sri lanka": "🇱🇰",
	"sudan": "🇸🇩",
	"sweden": "🇸🇪",
	"switzerland": "🇨🇭",
	"syria": "🇸🇾",
	"sierra": "🇸🇱",

	"taiwan": "🇹🇼",
	"tajikistan": "🇹🇯",
	"tanzania": "🇹🇿",
	"thailand": "🇹🇭",
	"tunisia": "🇹🇳",
	"turkey": "🇹🇷",
	"turkmenistan": "🇹🇲",

	"uganda": "🇺🇬",
	"ukraine": "🇺🇦",
	"united arab emirates": "🇦🇪",
	"united kingdom": "🇬🇧",
	"usa": "🇺🇸",
	"uruguay": "🇺🇾",
	"uzbekistan": "🇺🇿",

	"venezuela": "🇻🇪",
	"vietnam": "🇻🇳",

	"yemen": "🇾🇪",
	"zambia": "🇿🇲",
	"zimbabwe": "🇿🇼",
}

func GetCountryWithFlag(countryName string) (string, string) {
	cleanName := strings.ToLower(strings.Fields(countryName)[0])
	flag, ok := flagMap[cleanName]
	if !ok {
		return "🌐", "🌐 " + countryName
	}
	return flag, flag + " " + countryName
}